### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by muhammadasadalvi** [ArslanAmeer/angular-syn-boilerplate#7]
![image](https://github.com/ArslanAmeer/angular-boilerplate/assets/72218774/9cbb30dc-5b3a-49cd-8e9b-44e341da3dbd)

**Comment by ArslanAmeer** [comment]
Hi @muhammadasadalvi,

Thank you for reporting this issue. I'm glad to hear that you're using my template repository. I've investigated the issue, and I'm currently working on a fix. I expect to have it fixed in the next push.

In the meantime, if you have any other questions or concerns, please don't hesitate to contact me.

Thanks,
Arslan
